### ISSUE TITLE
Overwrite CSS

### ISSUE THREAD

**Issue by ghost** [danizep/react-timeline#2]
Hi @danizep 

The class  .timeline-wrapper has some default styles that i don't need to use.

`
.timeline-wrapper {
    line-height: 1;
    margin-top: 100px;
    width: 100%;
    height: 50px;
    overflow: hidden;
    background-color: #F6F6F6;
    position: relative;
    border-radius: 5px;
    color: #cccccc;
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
}
`

Can i overwrite them on my stylesheet or it will be a problem?
Thanks in advance

**Comment by danizep** [comment]
You can overwrite the majority of the styles like: `margins`, `paddings`, `colors`, etc...

The most important styles are assigned programmatically so you should have no problem. However you should be careful messing with `widths`
